name: "example-service"
namespace: "a4e-example-service"

imageTag: "1236"

applicationPort: "8080"

ingressHost: default-route-openshift-image-registry.apps.{{ .Values.global.region }}{{ .Values.global.cluster-name }}.{{ .Values.global.environment }}.msp.worldpay.io

#serviceAccountName: a4e-example-service-sa

replicas: 3

resources:
  memoryRequests: 512Mi
  memoryLimits: 800Mi
  cpuRequests: 300m
  cpuLimits: 1000m

volumeMounts: []
#  - name: example-service-config-volume
#    mountPath: /app/application-config
#    readOnly: true
#  - name: example-service-vault-config-volume
#    mountPath: /app/application-secret
#    readOnly: true

volumes: []
#  - name: example-service-config-volume
#    mountPath: /app/application-config
#    configMap:
#      name: example-service-config
#  - name: example-service-vault-config-volume
#    secret:
#      secretName: example-service-vault-config

#environment:
#  SPRING_CONFIG_IMPORT: "file:/app/application-secret/vault-config.yaml"
#  SPRING_CONFIG_LOCATION: "classpath:/application.yml,/app/application-config/application.yml"

#secrets:
#  a4e-sessions-service:
#    - VAULT_ROLE_ID: vault-role-id
#    - VAULT_SECRET_ID: vault-secret-id
#    - VAULT_ROLE_NAME: vault-role-name
#  a4e-sessions-service-redis:
#    - REDIS_PASSWORD: redis-password

#Externalsecrets
#awsSecrets:
#  my-vault-name:
#    secrets:
#      - name: some-aws-secret-key
#        alias: MY_ENV_VAR
