#These global values would automatically be injected by CI
global:
  awsRegion: ""
  environment: ""
  clusterName: ""
  functionalEnvironment: ""
  # Allows Overriding the name of resources
  fullnameOverride: ""
  namespaceOverride: ""
  imageTag: "1236"

# These values will be customized by consumers
tenant: "a4e"
name: "example-service"

applicationPort: 8080

ingressHost: ""
healthEndpoint: /status

serviceAccountName: ""

replicas: 3

resources:
  memoryRequests: 512Mi
  memoryLimits: 800Mi
  cpuRequests: 300m
  cpuLimits: 1000m


volumes: [ ]
# - name: example-service-config-volume
#   mountPath: /app/application-config
#   configMap: example-service-config
#   readOnly: true
# - name: example-service-vault-config-volume
#   mountPath: /app/application-secret
#   secret: example-service-vault-config
#   readOnly: true
# - name: another-example-service-vault-config-volume
#   mountPath: /app/application-secret-item
#   secret: example-service-vault-config
#   readOnly: true
#   items:
#     - key: some-item.json
#       path: some-item.json
#       mode: 420

environment:
#  SPRING_CONFIG_IMPORT: "file:/app/application-secret/vault-config.yaml"
#  SPRING_CONFIG_LOCATION: "classpath:/application.yml,/app/application-config/application.yml"

secrets:
#  a4e-sessions-service:
#    - VAULT_ROLE_ID: vault-role-id
#    - VAULT_SECRET_ID: vault-secret-id
#    - VAULT_ROLE_NAME: vault-role-name
#  a4e-sessions-service-redis:
#    - REDIS_PASSWORD: redis-password

#Externalsecrets
awsSecrets:
  refreshInterval: 10m
#  serviceAccount: "aws-secret-manager-service-account"
#  secrets:
#    dev-aws-secret-manager-key:
#      - awsSecretPropertyKey: my-aws-secret-key-property # will pull this from aws
#        secretKey: keystore-password # will store as this in kubernetes secret
#        decodingStrategy: None #Will try to decode using this strategy See: https://external-secrets.io/v0.5.9/guides-decoding-strategy/
#      - awsSecretPropertyKey: 2my-aws-secret-key-property # will pull this from aws
#        secretKey: 2keystore-password # will store as this in kubernetes secret
#
