#These global values would automatically be injected by CI
global:
  awsRegion: ""
  environment: ""
  clusterName: ""
  functionalEnvironment: ""

# Allows Overriding the name of resources
fullnameOverride: ""

# These values will be customized by consumers
tenant: "a4e"
name: "example-service"

imageTag: "1236"

applicationPort: 8080

ingressHost: ""
healthEndpoint: /status

serviceAccountName: ""

replicas: 3

resources:
  memoryRequests: 512Mi
  memoryLimits: 800Mi
  cpuRequests: 300m
  cpuLimits: 1000m


volumes: []
# - name: example-service-config-volume
#   mountPath: /app/application-config
#   configMap: example-service-config
#   readOnly: true
# - name: example-service-vault-config-volume
#   mountPath: /app/application-secret
#   secret: example-service-vault-config
#   readOnly: true
# - name: another-example-service-vault-config-volume
#   mountPath: /app/application-secret-item
#   secret: example-service-vault-config
#   readOnly: true
#   items:
#     - key: some-item.json
#       path: some-item.json
#       mode: 420

#environment:
#  SPRING_CONFIG_IMPORT: "file:/app/application-secret/vault-config.yaml"
#  SPRING_CONFIG_LOCATION: "classpath:/application.yml,/app/application-config/application.yml"

#secrets:
#  a4e-sessions-service:
#    - VAULT_ROLE_ID: vault-role-id
#    - VAULT_SECRET_ID: vault-secret-id
#    - VAULT_ROLE_NAME: vault-role-name
#  a4e-sessions-service-redis:
#    - REDIS_PASSWORD: redis-password

#Externalsecrets
#awsSecrets:
#  my-vault-name:
#    secrets:
#      - name: some-aws-secret-key
#        alias: MY_ENV_VAR
