{{- if or .Values.awsSecrets -}}
{{- if or .Values.awsSecrets.serviceAccount -}}
{{- if or .Values.awsSecrets.secrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ include "java.namespace" . }}
  name: {{ include "java.fullname" . }}-external-secrets
  labels:
    {{- include "java.labels" . | nindent 4 }}
spec:
  refreshInterval: {{.Values.awsSecrets.refreshInterval}}
  secretStoreRef:
    name: {{ include "java.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "java.fullname" . }}-secrets #The name of the kubernetes secret object
    creationPolicy: Owner
  data:
{{- range $awsSecretName, $props := .Values.awsSecrets.secrets -}}
{{- range $entry := $props -}}
{{- $awsSecretsMap := dict -}}
{{- range $awsSecretKeyProperty, $value := $entry -}}
{{- $_ := set $awsSecretsMap $awsSecretKeyProperty $value -}}
{{- range $kubernetesSecretKey, $val := $awsSecretsMap }}
    - secretKey: {{ $kubernetesSecretKey | quote}}
      remoteRef:
        key: {{ $awsSecretName | quote}}
        property: {{ $val | quote }}
        decodingStrategy: Auto #Because the secret might already be encoded as Base64, e.g if it is a file
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
