{{- if or .Values.awsSecrets -}}
{{- if or .Values.awsSecrets.serviceAccount -}}
{{- if or .Values.awsSecrets.secrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ include "java.namespace" . }}
  name: {{ include "java.fullname" . }}-external-secrets
  labels:
    {{- include "java.labels" . | nindent 4 }}
spec:
  refreshInterval: {{.Values.awsSecrets.refreshInterval}}
  secretStoreRef:
    name: {{ include "java.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "java.fullname" . }}-secrets #The name of the kubernetes secret object
    creationPolicy: Owner
  data:
{{- range $awsSecretName, $props := .Values.awsSecrets.secrets -}}
    {{- range $props }}
    - secretKey: {{ .secretKey | quote}}
      remoteRef:
        key:  {{ tpl $awsSecretName $ | quote }}
        property: {{ .awsSecretPropertyKey | quote }}
        decodingStrategy: {{ default "None" .decodingStrategy | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
