apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "java.fullname" . }}
  labels:
    {{- include "java.labels" . | nindent 4 }}
spec:
  maxUnavailable: 0
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      {{- include "java.selectorLabels" . | nindent 6 }}
