apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{ include "java.namespace" . }}
  name: {{ include "java.fullname" . }}
  labels:
    {{- include "java.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
{{ if .Values.ingressHost}}
  host: {{ tpl .Values.ingressHost . | lower}}
{{else}}
  {{ if .Values.global.functionalEnvironment}}
  host: "{{ include "java.fullname" . }}-{{ .Values.global.functionalEnvironment }}.apps.{{ .Values.global.awsRegion }}-{{ .Values.global.clusterName }}.{{ .Values.global.environment }}.msp.worldpay.io"
  {{else}}
  host: "{{ include "java.fullname" . }}-{{ include "java.namespace" . }}.apps.{{ .Values.global.awsRegion }}-{{ .Values.global.clusterName }}.{{ .Values.global.environment }}.msp.worldpay.io"
{{end}}
{{end}}
  path: "/"
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "java.fullname" . }}
    weight: 100
  wildcardPolicy: None
