apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{.Values.namespace}}
  name: {{ include "java.fullname" . }}
  labels:
    {{- include "java.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
  host: {{.Values.ingressHost}}
  path: "/"
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "java.fullname" . }}
    weight: 100
  wildcardPolicy: None
