{{- if or .Values.awsSecrets }}
{{- if or .Values.awsSecrets.serviceAccount }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "java.fullname" . }}-secret-store
  namespace: {{ include "java.namespace" . }}
  labels:
    {{- include "java.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.awsSecrets.serviceAccount }}
{{- end }}
{{- end }}
