kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{ include "java.fullname" . }}
  labels:
    {{- include "java.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{.Values.applicationPort}}
      protocol: TCP
      targetPort: {{.Values.applicationPort}}
  selector:
    {{- include "java.labels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
